baseURL = "https://nicolas-ricc.github.io/"
publishDir = "docs"
defaultContentLanguage = "es"
enableEmoji = true
summaryLength = 30

[frontmatter]
  date = ["date", "publishDate"]
  lastmod = ["lastmod"]
  publishDate = ["publishDate", "date"]

[pagination]
  pagerSize = 5

[taxonomies]
  tag = "tags"

[server]
  disableBrowserError = false
  [[server.headers]]
    for = "/**"
    [server.headers.values]
      Cache-Control = "no-cache"
